### ISSUE TITLE
请问feapder1.8.9是否支持自定义下载器

### ISSUE THREAD

**Issue by Sc-seven** [Boris-code/feapder#270]
**需知**
feapder版本为1.8.9
**问题**
目的为了通过curl_cffi对存有JA3指纹网站爬取，
尝试使用自定义下载器，发现没有生效。
**截图**
![image](https://github.com/user-attachments/assets/fda79fde-3049-4a78-bbfa-1cc047119733)
**代码**

```python
python3.9
```

**Comment by cidiry** [comment]
```python
from curl_cffi import requests as cffi_requests
import random

aaa = [
    "edge99",
    "edge101",
    "chrome99",
    "chrome100",
    "chrome101",
    "chrome104",
    "chrome107",
    "chrome110",
    "chrome116",
    "chrome119",
    "chrome120",
    "chrome123",
    "chrome124"
]

from feapder.network.downloader.base import Downloader
from feapder.network.response import Response


class RequestsDownloader(Downloader):
    def download(self, request) -> Response:
        response = cffi_requests.request(
            method=request.method,
            url=request.url,
            impersonate=random.choice(aaa),  # 随机选择一个浏览器指纹
            **request.requests_kwargs
        )
        response = Response(response)
        return response
```
```python
import feapder
from feapder.network.response import Response

class AirSpiderDemo(feapder.AirSpider):
    __custom_setting__ = dict(
        DOWNLOADER="downloader.cdy_downloader.RequestsDownloader"
    )

    def start_requests(self):
        url = "https://tls.browserleaks.com/json"
        yield feapder.Request(url=url, method="GET")


    def parse(self, request, response: Response):
        print(response.text)
        print(response)


if __name__ == "__main__":
    spider = AirSpiderDemo(thread_count=1)
    spider.start()
```
报错
```
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\74423\miniconda3\envs\amazon_scrapy\lib\site-packages\feapder\core\parser_control.py", line 550, in deal_request
    request.get_response()
  File "C:\Users\74423\miniconda3\envs\amazon_scrapy\lib\site-packages\feapder\network\request.py", line 406, in get_response
    response = self._downloader.download(self)
  File "C:\Users\74423\PycharmProjects\amazon_feapder_sys\amazon_crawl_project\downloader\cdy_downloader.py", line 33, in download
    response = self.session.request(
  File "C:\Users\74423\miniconda3\envs\amazon_scrapy\lib\site-packages\curl_cffi\requests\session.py", line 1074, in request
    stream_task = self.executor.submit(perform)
  File "C:\Users\74423\miniconda3\envs\amazon_scrapy\lib\concurrent\futures\thread.py", line 169, in submit
    raise RuntimeError('cannot schedule new futures after '
RuntimeError: cannot schedule new futures after interpreter shutdown
```

有没有大佬指点下
