### ISSUE TITLE
ModuleNotFoundError: No module named 'utils'

### ISSUE THREAD

**Issue by geilige** [Boris-code/feapder#44]
环境
Python 3.7.8 
mac os 10.15.7
pycharm 2020.3.5

报错操作
pip3 install feapder安装好后
终端执行
feapder create -s first_spider

(venv) ➜  Spiders feapder create -s first_spider
Traceback (most recent call last):
  File "/PycharmProjects/Spiders/venv/bin/feapder", line 5, in <module>
    from feapder.commands.cmdline import execute
  File "/PycharmProjects/Spiders/venv/lib/python3.7/site-packages/feapder/__init__.py", line 28, in <module>
    from feapder.core.spiders import Spider, BatchSpider, AirSpider
  File "/PycharmProjects/Spiders/venv/lib/python3.7/site-packages/feapder/core/spiders/__init__.py", line 13, in <module>
    from feapder.core.spiders.air_spider import AirSpider
  File "/PycharmProjects/Spiders/venv/lib/python3.7/site-packages/feapder/core/spiders/air_spider.py", line 14, in <module>
    import feapder.utils.tools as tools
  File "/PycharmProjects/Spiders/venv/lib/python3.7/site-packages/feapder/utils/tools.py", line 46, in <module>
    from feapder.utils.email_sender import EmailSender
  File "/PycharmProjects/Spiders/venv/lib/python3.7/site-packages/feapder/utils/email_sender.py", line 18, in <module>
    from utils.log import log

我在feapder/utils/email_sender.py改成from feapder.utils.log import log 正常了

**Comment by Boris-code** [comment]
> 环境
> Python 3.7.8
> mac os 10.15.7
> pycharm 2020.3.5
> 
> 报错操作
> pip3 install feapder安装好后
> 终端执行
> feapder create -s first_spider
> 
> (venv) ➜ Spiders feapder create -s first_spider
> Traceback (most recent call last):
> File "/PycharmProjects/Spiders/venv/bin/feapder", line 5, in
> from feapder.commands.cmdline import execute
> File "/PycharmProjects/Spiders/venv/lib/python3.7/site-packages/feapder/**init**.py", line 28, in
> from feapder.core.spiders import Spider, BatchSpider, AirSpider
> File "/PycharmProjects/Spiders/venv/lib/python3.7/site-packages/feapder/core/spiders/**init**.py", line 13, in
> from feapder.core.spiders.air_spider import AirSpider
> File "/PycharmProjects/Spiders/venv/lib/python3.7/site-packages/feapder/core/spiders/air_spider.py", line 14, in
> import feapder.utils.tools as tools
> File "/PycharmProjects/Spiders/venv/lib/python3.7/site-packages/feapder/utils/tools.py", line 46, in
> from feapder.utils.email_sender import EmailSender
> File "/PycharmProjects/Spiders/venv/lib/python3.7/site-packages/feapder/utils/email_sender.py", line 18, in
> from utils.log import log
> 
> 我在feapder/utils/email_sender.py改成from feapder.utils.log import log 正常了

感谢提出的问题，已修复, 请安装 1.3.9的版本
```
pip3 install feapder==1.3.9 -i https://pypi.org/simple/
```
