### ISSUE TITLE
bug反馈，关于requests的版本问题。

### ISSUE THREAD

**Issue by D1rtyDann** [Boris-code/feapder#92]
```python3
Traceback (most recent call last):
  File "/home/xh/miniconda3/envs/py37/lib/python3.7/site-packages/feapder/core/parser_control.py", line 137, in deal_requests
    if not setting.RESPONSE_CACHED_USED
  File "/home/xh/miniconda3/envs/py37/lib/python3.7/site-packages/feapder/network/request.py", line 378, in get_response
    response = requests.request(method, self.url, **self.requests_kwargs)
  File "/home/xh/miniconda3/envs/py37/lib/python3.7/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/xh/miniconda3/envs/py37/lib/python3.7/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/xh/miniconda3/envs/py37/lib/python3.7/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/home/xh/miniconda3/envs/py37/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/xh/miniconda3/envs/py37/lib/python3.7/site-packages/urllib3/connectionpool.py", line 696, in urlopen
    self._prepare_proxy(conn)
  File "/home/xh/miniconda3/envs/py37/lib/python3.7/site-packages/urllib3/connectionpool.py", line 964, in _prepare_proxy
    conn.connect()
  File "/home/xh/miniconda3/envs/py37/lib/python3.7/site-packages/urllib3/connection.py", line 359, in connect
    conn = self._connect_tls_proxy(hostname, conn)
  File "/home/xh/miniconda3/envs/py37/lib/python3.7/site-packages/urllib3/connection.py", line 506, in _connect_tls_proxy
    ssl_context=ssl_context,
  File "/home/xh/miniconda3/envs/py37/lib/python3.7/site-packages/urllib3/util/ssl_.py", line 432, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)
  File "/home/xh/miniconda3/envs/py37/lib/python3.7/site-packages/urllib3/util/ssl_.py", line 474, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock)
  File "/home/xh/miniconda3/envs/py37/lib/python3.7/ssl.py", line 423, in wrap_socket
    session=session
  File "/home/xh/miniconda3/envs/py37/lib/python3.7/ssl.py", line 827, in _create
    raise ValueError("check_hostname requires server_hostname")
ValueError: check_hostname requires server_hostname
```
系统： WSL ubuntu 20.04
python版本： 3.7.10
运行即报错，系统当前requests版本==2.25.0，stackoverflow找到解决方案，降级requests到2.20.0后解决。建议修改requirements中对requests版本的限制。

**Comment by D1rtyDann** [comment]
>= 2.20.0就有可能是2.25.0，然后出现该错误.

**Comment by Boris-code** [comment]
> ```
> >= 2.20.0就有可能是2.25.0，然后出现该错误.
> ```

文档里有写： http://feapder.com/#/question/%E8%AF%B7%E6%B1%82%E9%97%AE%E9%A2%98
